version: "2.0"
services:
  auth:
    image: recepies_auth
    ports:
      - "3002:3002"
    volumes:
      - ./certs/private.rsa:/private.rsa:ro
    environment:
      - MONGODB_HOST=172.17.0.1
      - DATABASE=recepies
      - KEYFILE=/private.rsa
